spring:
  application:
    name: eureka-provider
  profiles: node1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      host-mark: running-host

ribbon:
  eureka:
    enabled: true

server:
  port: 8087

mybatis:
  type-aliases-package: com.example.spring.cloud.netflix.provider.domain
  mapper-locations: classpath:mapper/*.xml

---
server:
  port: 7071

spring:
  profiles: node2
  application:
    name: eureka-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      host-mark: running-host

ribbon:
  eureka:
    enabled: true

---
server:
  port: 7072

spring:
  profiles: node3
  application:
    name: eureka-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      host-mark: gray-host

ribbon:
  eureka:
    enabled: true