spring:
  application:
    name: eureka-consumer
  sleuth:
    baggage-keys:  # 注意, Sleuth2.0.0之后, baggage的 key 必须在这里配置才能生效
      - SessionId
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8089

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 暴露 hystrix.stream 接口
management:
  endpoints:
    web:
      exposure:
        include: "*,hystrix.stream"

feign:
  hystrix:
    enabled: true
